### ISSUE TITLE
Incorrect Class Conversion Table Generation

### ISSUE THREAD

**Issue by soranoo** [soranoo/next-css-obfuscator#11]
Sorry, I have a problem unrelated to this issue, which is `caching`.

You know, every time you `run build` the obfuscate process will start from the beginning, meaning the `random obfuscated classes` will be completely different from the previous time. This causes nextjs `cache` related issue.

If a user has visited my page before, then after I update (new deployed), and they reload the page without clearing the cache, it will look like this:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/2912d931-e5ec-48b7-b960-13eaf4f66ebe)

And no matter how many times they try to 'refresh' the website, it will still look the same.

Unless they press `Ctrl + Shift + R` (aka `hard reload`), the site is updated.

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/e834c516-95f1-4af0-a4e3-8310b38d9493)

Even when I try `view page source` without `hard reload`, the css file doesn't have any new obfuscated class, which causes an error like my website doesn't have `css` at all.

Do you have the same problem in your version of `Next Js`, or do you have any advice for me, I've been searching for it all night.

_Originally posted by @hoangnhan2ka3 in https://github.com/soranoo/next-css-obfuscator/issues/10#issuecomment-1925819091_
            
---

Additional Infomation-
- Obfuscated selectors got obfuscated again ``conversion.json``

**Comment by hoangnhan2ka3** [comment]
> The problem probably only occurs when I enable `next-css-obfuscator`.
> 
> If you don't enable it from the beginning, the TW classes will just update the new values ​​after each deployment, and the old classes don't need to be changed, and it will be cached, I think.

**Comment by hoangnhan2ka3** [comment]
Bruhh is that easy ?=))), the problem may actually be `caching`, I don't see that being fixed in `2.1.5`, are there any more steps needed?

**Comment by soranoo** [comment]
If yes, then that is out of the scope of this package.

BUT the issue was just caused by the different obfuscation results in every run.

**Comment by hoangnhan2ka3** [comment]
Yes, it's annoying.

I think I'll split the current repo into a separate repo to be the source for hoangnhan.co.uk, it seems to be enough to be considered a `demo site`.

After that I thought I would have to turn this plugin off and turn it back on when everything is done, or I need too `hard refresh` every time deployed 😄

**Comment by hoangnhan2ka3** [comment]
Yesss, I think we need to do an option opposite to `refreshClassConversionJson`, I mean just updating new classes, that could also help reduce the overall obfuscate time, even though it is already very fast 👀

**Comment by soranoo** [comment]
```js
// next-css-obfuscator.config.cjs

module.exports = {
    //...
    refreshClassConversionJson: false,
    //...
};

```

**Comment by hoangnhan2ka3** [comment]
Haha what a beautiful prospect

**Comment by hoangnhan2ka3** [comment]
I never even `enable` the `refreshClassConversionJson` part sir 🥲

**Comment by soranoo** [comment]
That 

> Yesss, I think we need to do an option opposite to `refreshClassConversionJson`, I mean just updating new classes, that could also help reduce the overall obfuscate time, even though it is already very fast 👀
> 
> Now:
> 
> ![image](https://private-user-images.githubusercontent.com/147973044/302123269-4c26ea76-da7a-49d4-b506-475b2f9ccda6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNjk3OTAsIm5iZiI6MTcwNzA2OTQ5MCwicGF0aCI6Ii8xNDc5NzMwNDQvMzAyMTIzMjY5LTRjMjZlYTc2LWRhN2EtNDlkNC1iNTA2LTQ3NWIyZjljY2RhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxNzU4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjFlZjBkZDNlYzIxOThhYjkzMWEyMGY3Y2Q4M2IyNTY3OTVmYWQzNWQ1NGUwMDJhYWFjN2NiZjgzNTU4MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lkwqJhOm9BJfkPgg7q8u6YvP-Y0kor39FrEDAucCZ9k)
> 
> In expected:
> 
> ```
> Updated 02 more CSS rules to a6ee7635e9d39b73.css
> ```

Your expectations will never happen. NEXT JS generate a brand new CSS file in every build

**Comment by soranoo** [comment]
> I never even set the `refreshClassConversionJson` to `true` sir 🥲
> 
> Every time I want to try 'run build', I delete the old `.next/cache` folder and `css-obfuscator` folder before running the command. This makes me feel safer.


That is the issue I mentioned as follows.

> If yes, then that is out of the scope of this package.
> 
> BUT the issue was just caused by the different obfuscation results in every run. In other words, this is due to the incorrect behaviour of the `refreshClassConversionJson` option.

**Comment by hoangnhan2ka3** [comment]
U mean I should set it to `true` when deploying or is there an error in `refreshClassConversionJson`?

Perhaps there is no way to preserve the previously obfuscated class name? (based on the previous conversion.json file?), if possible, it seems that the pre-production steps will be more cumbersome hmm 🤔

**Comment by soranoo** [comment]
Please reference to [📖 Config Options](https://github.com/soranoo/next-css-obfuscator?tab=readme-ov-file#-config-options-reference). 

The obfuscator will use the old table if `refreshClassConversionJson = false` and push new obfuscation to the table if needed. Otherwise( if `refreshClassConversionJson = true`), a new table will be generated with brand new obfuscated selectors.

**Comment by hoangnhan2ka3** [comment]
But the problem is that `Vercel` will build the `css-obfuscator` folder from scratch every time it is deployed. Am I right?

And I've also included the `css-obfuscator` folder in .gitignore, should I? If not, do I have to run `run build` every time I deploy to update `conversion.json`?

Can you briefly recount the most accurate workflow for me?

**Comment by soranoo** [comment]
The deployment procedure is up to you.

But I will add `css-obfuscator` to `.gitignore` and let Vercel do the job.

**Comment by hoangnhan2ka3** [comment]
Okay, as I mentioned

> But the problem is that `Vercel` will build the `css-obfuscator` folder from scratch every time it is deployed. Am I right?

And

> I've also included the css-obfuscator folder in .gitignore

Present:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/9c9e1561-cc24-40dc-9409-a059c3dbe180)

Then I edited a letter in `/home`, then deployed again

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/899383a9-f494-4f49-9405-0888eb2109f7)

So what u mean

> The obfuscator will use the old table if refreshClassConversionJson = false and push new obfuscation to the table if needed.

Is that true or did I set it up wrong somewhere?

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/783d3bf4-8ee8-4d3e-abd2-ac40e2f18330)

`.gitignore`:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/61e41162-16f2-4e90-a7d9-23754cfb435c)

`GitHub repo`:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/7022173e-129e-48d0-813e-5adb387dd8fc)

**Comment by soranoo** [comment]
Vercel will download the repo to an empty folder(kind of) and everything has to be generated from scratch so you can see different obfuscated class names.

I can add a predictable obfuscation mode, tell me if u needed it.

**Comment by hoangnhan2ka3** [comment]
What u mean `predictable` 😄, any ref?

I just ran `run build` twice, it's true that it only updates the new class, you're right.

But I wonder, when I deploy the whole `css-obfuscator` folder, what happens? Let me check.

Perhaps `run build` before deploying wouldn't be such a bad idea if it solved the `caching` problem

**Comment by soranoo** [comment]
`predictable` same input same output

**Comment by hoangnhan2ka3** [comment]
Is there any way for `Vercel` to keep the old resources? Even though they say they do, perhaps the `npm install` process refreshes these resources each time they deploy?

And I just found out, if `refreshClassConversionJson` is `false`, yes, it will update the new class if there is one and also keep the old obfuscated class intact. But when I delete the newly added class and `run build` again, the log says `{previous CSS rules} - 1`

eg: 236 to 235

But when I check `conversion.json` the class has not been removed

**Comment by hoangnhan2ka3** [comment]
Oh no, even when I uploaded `css-obfuscator` folder, `Vercel` didn't respect my old `css-obfuscator` one, they generated brand new class:

First deployment:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/5dd2089c-3a3b-496b-b60b-68a20f4a8ba4)

I update something not related and deploy again:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/ca9f430e-bcb6-4aa4-959b-894deb249f46)

It kept the old class, but:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/e67596d7-b8e0-4bd2-b0a3-8dc8738a4a07)

**Comment by hoangnhan2ka3** [comment]
What's wrong 🤡🤡🤡

**Comment by soranoo** [comment]
Try redeploy with the `Use existing build cache` option disabled.

**Comment by hoangnhan2ka3** [comment]
Oh sorry, it's my fault again. I should have made a `hard reload` to simulate a new user entering the site for the first time before doing the steps above, and I forgot about that. Now everything seems to be fine, there's only the problem of 'not automatically deleting the class'

**Comment by soranoo** [comment]
This is an expected behaviour of the obfuscator to keep the removed selector obfuscation.

**Comment by hoangnhan2ka3** [comment]
Do u mean to keep unnecessary classes for later use?

Btw...

Yeah, and there's probably no better way than updating `conversion.json` manually (I can even give custom names to the classes I want 😄), just `run build ` is really long, but if you don't do that the plugin won't run because it gets the build data from `.next`

**Comment by hoangnhan2ka3** [comment]
It's okay, at least it lives up to my expectations ✨

**Comment by hoangnhan2ka3** [comment]
Hey @soranoo , do you plan to also obfuscate `id` too? like `PostCSS-Obfuscator`

**Comment by soranoo** [comment]
not now, I may do it after fixing the [Partial Obfuscation](https://github.com/soranoo/next-css-obfuscator?tab=readme-ov-file#-known-issues)

**Comment by soranoo** [comment]
@hoangnhan2ka3 
Let out the latest update, and the following
https://github.com/soranoo/next-css-obfuscator?tab=readme-ov-file#6-how-to-deal-with-css-cache-in-paas-like-vercel

Hope this can help you out.

**Comment by hoangnhan2ka3** [comment]
This means just letting the `Math.random().toString()` expression do its thing without worrying about whether it will change or if I need to create my own `random string' ` and put it here?

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/d87651cc-870d-4513-825f-a5e44700aa84)

**Comment by hoangnhan2ka3** [comment]
Oh I see the class name still changes after each deployment but maybe the `caching` problem is gone, how does it work?

**Comment by hoangnhan2ka3** [comment]
I put the `css-obfuscator` folder into `.gitignore` and I see the class name still changes after each deployment, so `caching` problem still there hmmm

**Comment by soranoo** [comment]
As I mentioned in the [💡 Tips](https://github.com/soranoo/next-css-obfuscator) section, you have to PROVODE  a seed.

**Comment by hoangnhan2ka3** [comment]
Yes I tried

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/d2f003cf-3ce5-4240-8a28-3408af9d6d4c)

But useless

**Comment by hoangnhan2ka3** [comment]
Another case is that I still deploy the `css-obfuscator` folder but I no longer need to `run build` before deploying it.

But it doesn't look very promising...

**Comment by soranoo** [comment]
> I think 'generating a seed' seems like a good and promising idea, just like the seed in 'Stable Diffusion'.
> 
> But is it really as easy as you think, like having to prepare the class name in advance for all possible situations?

Would you mind showing me how others can reverse the random string to class name?

**Comment by hoangnhan2ka3** [comment]
Sorry, I can't because that's not my expertise.

Have you ever used `Stable Diffusion`, `seed` in SD will look like this:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/aba76378-cb99-434b-8418-0eec85ba4ce5)

It means that if the value in the `seed` box is `-1` then each time `generate` the image will use a different `number string` (random).

And if you fill in the `seed` box with a certain sequence of numbers (it doesn't matter what the number and magnitude limit is: it can be 1, 11, 111 or 9516515132159). So each time you `generate` the image with the same initial `prompt` the image will look the same until you change to a different `seed`.

That's what I expect if you can do it, it's really difficult just imagining it

**Comment by hoangnhan2ka3** [comment]
So one last time

> can I safely put the css-obfuscator folder into .gitignore now?

And let it automatically added `just new` classes?

**Comment by soranoo** [comment]
`css-obfuscator` is generated so it is safe to put it into `.gitignore`

**Comment by hoangnhan2ka3** [comment]
And I hope that in future 'deploys', the old class names will remain the same as last time and only 'new classes' will be added if any?

That's what `predictable` mode does, right? I need you to confirm so I can move the `css-obfuscator` folder into .gitignore for the 3rd time today 🙂

And I need you to confirm one more issue:

`generatorSeed` needs to be a number between `0` and `1` like `0.132156479` (separated by a dot `.`), right?

**Comment by soranoo** [comment]
Please read the [📖 Config Options Reference](https://github.com/soranoo/next-css-obfuscator?tab=readme-ov-file#-config-options-reference) carefully!!!!

1. "predictable" means the obfuscated class name will be the same if the same CSS file is provided.
2. `generatorSeed` is a STRING, just put some random characters you like

**Comment by hoangnhan2ka3** [comment]
But every time you deploy, `Vercel` will create a new css file

> if the same CSS file is provided

, so is `predictable mode` useless in `production`?

**Comment by soranoo** [comment]
OK, sorry for misleading, it should be,
> "predictable" means the obfuscated class name will be the same if the same CSS content is provided.

**Comment by hoangnhan2ka3** [comment]
1. `same content`, do you mean the `seed` that I provide to the `config file` initially will save the current content of the CSS file, then if I add anything new it will only obfuscate the new classes. That's it, right? And then it loops the process again?

2. Or when I add a new class and the content is changed, the obfuscate process will completely refresh the class name?

Please choose 1 or 2, I hope it's 1

**Comment by soranoo** [comment]
Neither is correct, the obfuscation is expected to run after the build is completed. A new conversion table will be generated every time but with the given seed. If the seed is set and the sequence of CSS selectors inside the CSS file is the same as the last build then the table will be the same. So if a new class is added and Tailwind puts it inside the sequence(break the old sequence), an obfuscated class name will be assigned and NEXT JS will give another file name with the new CSS content which will invalidate the old cache.

**Comment by hoangnhan2ka3** [comment]
The answer I want to hear from you is that if a new `TW class` is added, all the `old class names` will not be kept and will be changed to `different class names`, right?

If that's the case, then I think you should leave `predictable` out, or merge it with `random` if there really is something better than `random`.

**Comment by soranoo** [comment]
1. PLEASE READ THE COMMENT CAREFULLY, short answer: can be different/ the same
2. Yes, Im going to merge `predictable` to `random` and `simplify` mode

**Comment by hoangnhan2ka3** [comment]
I know but

> an obfuscated class name will be assigned and NEXT JS will give another file name with the new CSS content which will invalidate the old cache (based on my experience).

What do u mean `assigned`, and don't worry about `caching` problem, it's too soon.

I want to know the result, a solid answer, about what would happen if a new TW class were added.

**Comment by soranoo** [comment]
Why don't I make your wish come true instead of explaining it in the text?

Let's move to #14
