### ISSUE TITLE
`Different` class names are but `Same` obfuscated name

### ISSUE THREAD

**Issue by hoangnhan2ka3** [soranoo/next-css-obfuscator#18]
Version: `v2.2.2 released`

As the title:

<img width="322" alt="Screenshot 2024-02-06 101425" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/e03459c8-6974-4d4a-9545-11fbe6560376">

I tried it twice so I think this is not a `1% random` error case (cuz I don't know if this plugin supports making sure the class names won't overlap)

The `.xjun0e` class (aka `.pr-[1.41dvw]`) should be in `<main>` tag ✅:

<img width="460" alt="image" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/6c54ef01-53ec-4426-b6eb-1fe4e6e313cd">

Below, right where `.side-box-line` should be, there should be another `obfuscated class name`. But it has the same name as `.pr-[1.41dvw]` ⛔:

<img width="560" alt="image" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/db79e908-4ec4-4e9c-996a-a91cdc62175f">

_Note: `.side-box-line` is just a className, no direct styles were applied to it, it only gets styles through class like this `[&_.side-box-line]:left-0` and this class is also not in `<main>` (I explain like this to avoid misunderstanding)_

That causes `.side-box-line`, which should look like this ✅:

<img width="119" alt="image" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/8de65f2c-22f8-4e92-9f69-1a4da77b480a">

to look like this ⛔:

<img width="122" alt="image" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/0948a5e1-6000-446b-a694-bd2f6bc11111">

The green color is the `padding-right` effect:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/d47f7ced-928f-49c7-b26c-87a5d6947a5b)

**Comment by hoangnhan2ka3** [comment]
https://github.com/soranoo/next-css-obfuscator/assets/147973044/7d2cff1c-413a-4db1-a846-38fe17b30d91

This feature doesn't seem really stable yet, although I see this as a feature that would be really great 🤩.

This is the `seed` I used in the video:

```
module.exports = {
   ...
    generatorSeed: 848178188989999,
   ...
}
```

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/23c90a47-5ce7-4857-bb98-db68f1d22948)

**Comment by soranoo** [comment]
A new issue was created.
https://github.com/soranoo/recoverable-random/issues/1

**Comment by hoangnhan2ka3** [comment]
Perhaps for `seeds` with a large number of digits like I commented above, the error still occurs.

1. Is there a safety limit for the number of digits used in a `fixed seed`?

2. Is it true that every time you update a new version, if it's still the same `seed`, the `obfuscated class name` comes out different? I mean it's the same `seed` but after each update of `this plugin` the results will be different.

**Comment by hoangnhan2ka3** [comment]
Hi @soranoo, just because I'm too lazy to create a new issue, I'm commenting on the old bug here.

I think it's very rare that this happens, but is there any way to be sure it doesn't overlap anymore?

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/af69adac-034a-4730-bff5-92b94800b96e)

Package version `2.2.6`

I just hope this patch won't change the class name again, because it seems like you'll be editing the `recovery-random` package.

**Comment by soranoo** [comment]
It is not necessary to comment on both issues.

Any issue with random generation may related to the underlay random generation algo if a new algo is introduced the rng behaviour will be changed and a new class name will be generated.

If you want to keep the old class name for some reason, you can simply modify the JSON manually.

**Comment by hoangnhan2ka3** [comment]
> Added ClassName Duplication Check & New Random

Sounds cool!

Have you had time to push it to npm yet, or is there still work to be done?

I still think it's a good idea that you can have it check if there is a duplicate class in `conversion.json` and replace it with another random string.

However, I still wonder if I'm that unlucky, in

$36^6 = 2,176,782,336$

possible cases, I have 2 overlapping classes... or is it called luck?

**Comment by soranoo** [comment]
I found I forgot to pull it Sorry about that.

Do you mean the collision before the update?

**Comment by hoangnhan2ka3** [comment]
Yes, in `v2.2.6`

**Comment by hoangnhan2ka3** [comment]
🤔

<img width="708" alt="image" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/34c0c6f5-15a9-4855-b157-c328285f5b1c">

**Comment by soranoo** [comment]
You have to use `string` seed.

**Comment by hoangnhan2ka3** [comment]
omg when did I remove the `"` from `generatorSeed`😂, sorry for the brainless question.

**Comment by soranoo** [comment]
If it is no dulipcation report after 24hrs I will close this issue.

But plz feel free to comment here if it happened again.

**Comment by hoangnhan2ka3** [comment]
It seems like this bug needs to wait until someone "lucky" encounters the same situation as I mentioned above to be sure it works haha

**Comment by soranoo** [comment]
Yes, exactly. So I try my best to give response in any format to let the issue raiser know "someone" is care about it.
