### ISSUE TITLE
[BUG] Incorrect: `className` detect to `property's name` in useRef

### ISSUE THREAD

**Issue by hoangnhan2ka3** [soranoo/next-css-obfuscator#24]
**Type**
- [ ] Incorrect Class Name Extraction
- [x] Incorrect JavaScript Obfuscation
- [ ] Incorrect HTML Obfuscation
- [x] Incorrect CSS Obfuscation
- [ ] Others

**Checklist**
1. [x] Updated the package to the latest version
2. [x] Read all documentation
3. [x] No related issue
4. [x] Meaningful issue title

**Environment**
- Package Version: v.2.2.10
- Node Version: v.20.10.0

**Describe the bug**
`transform` property's name was obfuscated although it's not a className.

**To Reproduce**
...

**Expected behavior**
This is not a className so don't obfuscate it.

**Screenshots**

<img width="288" alt="Screenshot 2024-02-18 201306" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/0b3c69ea-1eac-47f3-8725-34b451772e0c">

**Config**
```cjs
module.exports = {
  enable: true,
  mode: "random",
  buildFolderPath: ".next",
  classConversionJsonFolderPath: "./css-obfuscator",
  refreshClassConversionJson: false,

  classLength: 6,
  classPrefix: "n",
  classSuffix: "",

  classIgnore: ["no-transition", "opa-hidden", /nprogress*/, /__.*/, /os-*/],

  allowExtensions: [".jsx", ".tsx", ".js", ".ts", ".html", ".rsc"],

  contentIgnoreRegexes: [/\.jsxs\)\("\w+"/g],

  whiteListedFolderPaths: [],

  blackListedFolderPaths: ["./.next/cache", "./src", "./public", "./tests"],

  enableMarkers: false,
  markers: ["obf"],
  removeMarkersAfterObfuscated: true,

  removeOriginalCss: true,

  generatorSeed: "84817818898",

  //! Experimental feature (Alpha)
  enableJsAst: false,

  logLevel: "info",
};
```

**Related files**

`Obfuscated` version:
[97fb199871848870.css.txt](https://github.com/soranoo/next-css-obfuscator/files/14322618/97fb199871848870.css.txt)

Without`obfuscated` version:
[97fb199871848870.css.txt](https://github.com/soranoo/next-css-obfuscator/files/14322627/97fb199871848870.css.txt)

**Demos (if any)**
N/A

**Additional context**

In `conversion.json`:

<img width="258" alt="Screenshot 2024-02-18 201226" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/435826bd-a624-483f-8f09-555ce70adaf1">

After `npm run build + start`

<img width="288" alt="Screenshot 2024-02-18 201306" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/50fc702f-b73d-4bce-848c-d3c8a5d24790">

Others:

<img width="746" alt="Screenshot 2024-02-18 201506" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/621eb1bc-70d0-4275-836a-74846e80eed8">

<img width="759" alt="Screenshot 2024-02-18 201549" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/fe25cb0b-50b9-4272-a2bd-b8751cf32370">

**Comment by soranoo** [comment]
As a temporary solution, add the following to the config
```js
classIgnore = ["transform "]
```

I will get back to the issue after a month.

**Comment by soranoo** [comment]
I would say it is the limitation of the non-AST method. You may turn on the `enableJsAst` or make use of the temporary solution mentioned above.
