### ISSUE TITLE
[Feature Request] Add the `regex` used to identify classes as one `config option`

### ISSUE THREAD

**Issue by hoangnhan2ka3** [soranoo/next-css-obfuscator#28]
**Checklist**
1. [x] Read all documentation
2. [x] No related request
3. [x] Meaningful issue title

**Is your feature request related to a problem? Please describe.**
With Tailwind, sometimes we can add some complex class names as we like, or add custom `variants` ([ref](https://tailwindcss.com/docs/plugins#adding-variants)) with "special" characters. So perhaps having an option for users to edit the `regex` of the class identification logic would be a good idea.

The truth is that sometimes I want to tweak something to see if it works or not, but I don't really know which one to touch 🥲.

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/2cfd1255-e78d-4f46-ac18-56084fe3ba4a)

**Describe the solution you'd like**

It seems like this plugin wants to target many different `UI libraries` and `frameworks`, not just NextJs w/ Tailwind. So you can refer to the implementation of [this VSCode extension](https://marketplace.visualstudio.com/items?itemName=Trapfether.tailwind-raw-reorder#:~:text=Tailwind%20Raw%20Reorder%20is%20an,can%20even%20sort%20entire%20workspaces.):

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/ef6c3086-bf3e-47e5-8ad7-ec5beae547e7)

And here is `settings.json` with its basic settings:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/c32262cf-d88f-49c1-bdaa-636541b946f3)

**Additional context**
If you have time then do it, I think it would be a good idea!

**Comment by hoangnhan2ka3** [comment]
Hey @soranoo, did you notice that 🤣

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/19f18c0b-0848-4dc4-923e-3a95a8006936)

**Comment by soranoo** [comment]
Just noticed. If version 2 is out and it covers most of the features this package has. I will consider archiving this repo. Looking forward to your work! @n4j1Br4ch1D

**Comment by soranoo** [comment]
But before it is out I will continue to maintain this pkg.

**Comment by soranoo** [comment]
> **Checklist**
> 
> 1. [x]  Read all documentation
> 2. [x]  No related request
> 3. [x]  Meaningful issue title
> 
> **Is your feature request related to a problem? Please describe.** With Tailwind, sometimes we can add some complex class names as we like, or add custom `variants` ([ref](https://tailwindcss.com/docs/plugins#adding-variants)) with "special" characters. So perhaps having an option for users to edit the `regex` of the class identification logic would be a good idea.
> 
> The truth is that sometimes I want to tweak something to see if it works or not, but I don't really know which one to touch 🥲.
> 
> ![image](https://private-user-images.githubusercontent.com/147973044/310504546-2cfd1255-e78d-4f46-ac18-56084fe3ba4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzYyMzEsIm5iZiI6MTcwOTgzNTkzMSwicGF0aCI6Ii8xNDc5NzMwNDQvMzEwNTA0NTQ2LTJjZmQxMjU1LWU3OGQtNGY0Ni1hYzE4LTU2MDg0ZmUzYmE0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxODI1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDY4MTBhZWU5ODc2YjRkM2M1ZmI0ZGY0NjBlMzM4NDFlODZiZTZkYTU5Y2E1ZGM2MTQyOTVlZDM5Yjk0MDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P3BLSJzAP9yyACU0bxO_rTdnL9EiTl173JEbEHNegLM)
> 
> **Describe the solution you'd like**
> 
> It seems like this plugin wants to target many different `UI libraries` and `frameworks`, not just NextJs w/ Tailwind. So you can refer to the implementation of [this VSCode extension](https://marketplace.visualstudio.com/items?itemName=Trapfether.tailwind-raw-reorder#:~:text=Tailwind%20Raw%20Reorder%20is%20an,can%20even%20sort%20entire%20workspaces.):
> 
> ![image](https://private-user-images.githubusercontent.com/147973044/310506658-ef6c3086-bf3e-47e5-8ad7-ec5beae547e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzYyMzEsIm5iZiI6MTcwOTgzNTkzMSwicGF0aCI6Ii8xNDc5NzMwNDQvMzEwNTA2NjU4LWVmNmMzMDg2LWJmM2UtNDdlNS04YWQ3LWVjNWJlYWU1NDdlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxODI1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWFlYTYzNmZlMDJiZjk3OGRlYWI4YmE5NDIyZmI5NDViOTI0ZmVhM2Q3ZWRlNjBmZGU4MzU4YWY3NjhmZjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5EO7Jqq-4LTn-SujJmR9_UrShdstfxsJPcQQdG_r5WU)
> 
> And here is `settings.json` with its basic settings:
> 
> ![image](https://private-user-images.githubusercontent.com/147973044/310506001-c32262cf-d88f-49c1-bdaa-636541b946f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzYyMzEsIm5iZiI6MTcwOTgzNTkzMSwicGF0aCI6Ii8xNDc5NzMwNDQvMzEwNTA2MDAxLWMzMjI2MmNmLWQ4OGYtNDljMS1iZGFhLTYzNjU0MWI5NDZmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxODI1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2U0ZDgxZmUxYjY1MjkxYTFjMjg5OGJiYzI4OTVkYTMxNmQxM2U5NjI5NzE1NDUxZGE0NGU4NDBhYWM1NDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p8V6_5fR6jqBT25rYiB7JLNu_RAgAKg13f90pruOsDU)
> 
> **Additional context** If you have time then do it, I think it would be a good idea!

I'm not going to expose the regexes behind the scenes. Many regexes are involved in getting the whole system to work. Once the regexes become accessible, it will definitely make the project much more difficult to maintain. 

If your special chara involves the class name extraction, you can check out the `extractClassFromSelector` function in `src/handlers/css.ts`.
