### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir './css-obfuscator'

### ISSUE THREAD

**Issue by sccofield** [soranoo/next-css-obfuscator#3]
Hey @soranoo, thank you so much for the beautiful work done so far.

At the moment, I used your settings as seen below. I can see that the tailwind classes have been obfuscated but i can't see the effect of the tailwind classes. 

postcss.config.js

```
const isObfscMode = process.env.NODE_ENV === 'obfuscation';

module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    'next-css-obfuscator/patched-postcss-obfuscator': {
      enable: isObfscMode,
      extensions: ['.jsx', '.tsx', '.js', '.ts', '.html'],
      formatJson: true, // 👈 must be true
      keepData: true, // 👈 must be true
      whiteListedPaths: [],
      blackListedPaths: ['./next/cache'],
      excludeAnyMatchRegex: [
        /\.next\/server\/pages\/api/,
        /_document..*js/,
        /_app-.*/,
      ],
      classIgnore: ['static'],
      callBack: function () {
        // @ts-ignore
        process.env.NODE_ENV = 'production'; // to make sure postcss-obfuscator doesn't re-run.
      },
    },
  },
};
```
<img width="1436" alt="Screenshot 2024-01-10 at 5 32 44 AM" src="https://github.com/soranoo/next-css-obfuscator/assets/12601490/c20d3a38-9935-4062-81c8-479414c31c31">

**Comment by soranoo** [comment]
Do you mean the page is broken after obfuscation?

**Comment by sccofield** [comment]
yea @soranoo the page is broken, the tailwind styles don't reflect on the page. 

I tried starting the process all over on another branch but  i am now getting this error when i run the obfuscate-build command

`Error: ENOENT: no such file or directory, scandir './css-obfuscator'`

**Comment by soranoo** [comment]
Which OS are you using?

**Comment by sccofield** [comment]
macbook

**Comment by soranoo** [comment]
I don't have any Apply device. I can't debug the issue but you may create the folder yourself and see what happens next.

**Comment by sccofield** [comment]
After creating the folder `css-obfuscator`, and running `npm run obfuscate-build`, it tells me `Obfuscation Obfuscation complete` , but no file is created in the folder.

**Comment by soranoo** [comment]
I have totally no idea why this happened. It works perfectly in my Docker Linux.

**Comment by soranoo** [comment]
Finally, I got the error.

To address this,
1. If there are 2 `postcss.config` remove one.

![image](https://github.com/soranoo/next-css-obfuscator/assets/46896789/2f89ef7b-1147-4d87-a144-ea684947ed6b)

**Comment by soranoo** [comment]
[v.2.0.0](https://github.com/soranoo/next-css-obfuscator/commit/53e99db69e3afc10d65d43b13524c1accaf8bf28) has been released.

**Comment by soranoo** [comment]
The issue will be closed, please open a new one if encounter it again.
