### ISSUE TITLE
Deployment on Netlify

### ISSUE THREAD

**Issue by billpebert** [soranoo/next-css-obfuscator#34]
Hi @soranoo 
i need help, i deployed a project to netlify and set to run the _next build && npm run obfuscate-build_
but this is the result
![image](https://github.com/soranoo/next-css-obfuscator/assets/70867121/cf483ccd-37df-41b8-9f47-b2d92aba64de)

**Comment by soranoo** [comment]
Sorry I can't track down how this error occurred with a general error. Please follow the bug report format.
