### ISSUE TITLE
Laravel Breeze NextJS: Laravel Doesn't work with this.

### ISSUE THREAD

**Issue by WavaDev** [soranoo/next-css-obfuscator#39]
The issue is that Laravel doesn't use npm start - it works right after using npm run build. However, the obfuscator runs after the build, so the application doesn't update.

**Comment by soranoo** [comment]
Please follow the bug report format.

**Comment by WavaDev** [comment]
> The issue is that Laravel doesn't use npm start - it works right after using npm run build. However, the obfuscator runs after the build, so the application doesn't update.

#40
