### ISSUE TITLE
MultiLine className

### ISSUE THREAD

**Issue by MrMarmo** [soranoo/next-css-obfuscator#4]
When having a className, in a .tsx, that spans multiple lines, if the last class name, in any line, doesn't have a space after it, it doesn't get replaced during the obfuscate-build.

fixed it with "```regex = new RegExp(`([\\s"'\\\`]|^)(${keyUse})(?=$|[\\s"'\\\`]|\\\\n)`, 'g');```" in utils.js

**Comment by soranoo** [comment]
The obfuscator does not directly work with the files inside the `src`. It only obfuscates code under the `.next` folder, which is the NextJS build folder. Version 2.0.0 will be out this weekend and you will get better docs, demos and config. Please wait for it.

**Comment by soranoo** [comment]
[v.2.0.0](https://github.com/soranoo/next-css-obfuscator/commit/53e99db69e3afc10d65d43b13524c1accaf8bf28) has been released.

**Comment by MrMarmo** [comment]
Sorry. i did mean in the .next folder. see how gap-2 has a "\n" in the compiled js. 

<img width="1153" alt="Screenshot 2024-01-21 at 2 08 03 PM" src="https://github.com/soranoo/next-css-obfuscator/assets/42856741/047a3130-ff23-4210-a1fb-ebd6b8e7b17c">

2.0 might have fixed this.

**Comment by soranoo** [comment]
Why there are \n in the compiled JS? This is not supposed to happen. May I have the related source code?

**Comment by MrMarmo** [comment]
maybe its just a mac thing. idk if it happening on linux. 
This is just a normal .tsx file compiled with "next build"

<img width="1115" alt="Screenshot 2024-01-21 at 2 18 17 PM" src="https://github.com/soranoo/next-css-obfuscator/assets/42856741/d9f4c6b3-c6cd-453a-9f80-8a07c5badf0c">

**Comment by MrMarmo** [comment]
ok, so setting line 151 in utils.js, in 2.0, to this ```regex = new RegExp(`([\\s"'\\\`]|^)(${keyUse})(?=$|[\\s"'\\\`]|\\\\n)`, 'g');``` fixes it still. but idk if i will break any thing else. prob not.

without change:
<img width="810" alt="Screenshot 2024-01-21 at 2 30 16 PM" src="https://github.com/soranoo/next-css-obfuscator/assets/42856741/2a6b4aa3-ba68-4ba0-9c48-8356d9d9bdbe">

with change:
<img width="773" alt="Screenshot 2024-01-21 at 2 31 23 PM" src="https://github.com/soranoo/next-css-obfuscator/assets/42856741/981597ba-f7a6-4baa-a10e-f118228cb4a4">

**Comment by soranoo** [comment]
I just updated the npm package. Check out the [v.2.0.1](https://www.npmjs.com/package/next-css-obfuscator)
