### ISSUE TITLE
Classes returned with original name in conditional rendering in JsAST

### ISSUE THREAD

**Issue by iamarpitpatidar** [soranoo/next-css-obfuscator#45]
**Type**
- [ ] Incorrect Class Name Extraction
- [X] Incorrect JavaScript Obfuscation
- [ ] Incorrect HTML Obfuscation
- [ ] Incorrect CSS Obfuscation
- [ ] Others

**Environment**
- Package Version: v.2.2.16
- Node Version: v.18

**Describe the bug**
upon conditional rendering classname are incorrect. returned original classname

**To Reproduce**
1. create a basic app with create next app
2. add this snipped
```jsx
const [isVisible, setIsVisible] = useState(false);
return (
    <div>
      <div className={`scroll-top ${isVisible ? 'visible' : ''}`}></div>
    </div>
)
```
4. See error in classes when state gets updated

**Expected behavior**
It should return obfuscated class name even after state update

**Screenshots**
![Screen Shot 2024-09-25 at 8 29 43 PM](https://github.com/user-attachments/assets/0c01ffbf-1e28-459e-8a8c-62adc135247f)

**Config**
```js
  enable: true,
  mode: "random",
  refreshClassConversionJson: false,
  allowExtensions: [".jsx", ".tsx", ".js", ".ts", ".html", ".rsc"],
  blackListedFolderPaths: [
    "./.next/cache",
    /\.next\/server\/pages\/api/,
    /_document.*js/,
    /_app-.*/,
    /__.*/,
  ],
  classConversionJsonFolderPath: './.next/css-obfuscator',
  removeOriginalCss: true,
  enableJsAst: true
```

**Comment by soranoo** [comment]
I can't reproduce this issue

Please check out
https://stackblitz.com/edit/next-css-obfuscator-issues-45

To Run it
1. Stop the console
2. Run > npm i && npm run build && npm run start

**Comment by iamarpitpatidar** [comment]
![Screen Shot 2024-09-27 at 6 01 52 PM](https://github.com/user-attachments/assets/d55dd05a-4673-4356-ab5b-a5b04e7c4da8)

@soranoo when I added the config file please check the class name is same `scroll-top`
```js
  module.exports = {
    enable: true,
    mode: 'random',
    refreshClassConversionJson: false,
    allowExtensions: ['.jsx', '.tsx', '.js', '.ts', '.html', '.rsc'],
    blackListedFolderPaths: [
      './.next/cache',
      /\.next\/server\/pages\/api/,
      /_document.*js/,
      /_app-.*/,
      /__.*/,
    ],
    classConversionJsonFolderPath: './.next/css-obfuscator',
    removeOriginalCss: true,
    enableJsAst: true,
  };
```

**Comment by soranoo** [comment]
I found I forgot to set the config up. A new Investigation will begin soon.

**Comment by soranoo** [comment]
Lets checkout v2.2.17.

**Comment by soranoo** [comment]
lets checkout `v2.2.18` ~
