### ISSUE TITLE
Accidently obfuscated HTML tag

### ISSUE THREAD

**Issue by soranoo** [soranoo/next-css-obfuscator#7]
One more :)))) Sorry I'm so annoying just pointing out the bug without doing anything to help you 🥲.

### **👉 `filter` tag inside `svg` tag:**

<img width="495" alt="Screenshot 2024-02-01 005032" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/bd148a48-bab6-4bba-bc9c-e46ecc505d65">

In the comments above, I had to put `filter` in `classIgnore` to not cause the `filter` tag to obfuscate, hmmm... I don't know why it detected `filter` tag as a class.

<img width="437" alt="Screenshot 2024-02-01 005433" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/358821da-aeee-4bba-b779-2e4d5b1c64c0">

In `conversion.json` file:

<img width="171" alt="Screenshot 2024-02-01 005736" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/5c65eef2-813e-4bf4-b155-086d985a42ea">

OMG is it really a class 🤯? How.

Note: `filter` attribute was not changed ✅:

<img width="127" alt="Screenshot 2024-02-01 010832" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/8f1cd8c2-22e0-4574-9948-40aa4637d6c3">

### **👉 Also with `iframe` tag:**

<img width="282" alt="Screenshot 2024-02-01 010014" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/3618b765-bc16-446f-b123-7f0fb89d4f21">

<img width="174" alt="Screenshot 2024-02-01 010221" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/29d0e2af-3d83-47f6-9cd9-c436213a41cf">

I thought it was an `element of HTML` huh?

<img width="504" alt="Screenshot 2024-02-01 010054" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/5791b8b6-a429-47f2-b7cd-37cb8e2ce815">

With `<filter>`:

<img width="241" alt="Screenshot 2024-02-01 010346" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/21ad0f89-3e9d-4e85-b081-2ba35fdc6797">

Without `<filter>`:

<img width="253" alt="Screenshot 2024-02-01 010400" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/c0db6058-6a12-4be6-ae8b-b2224af76310">

_Originally posted by @hoangnhan2ka3 in https://github.com/soranoo/next-css-obfuscator/issues/6#issuecomment-1919632415_

**Comment by soranoo** [comment]
It seems `filter` is a valid Tailwind class.
![image](https://github.com/soranoo/next-css-obfuscator/assets/46896789/c6b2bb6d-d27b-456e-ac71-48966b1eeb83)

I don't see where the issue is. The key obfuscation regex works very well.
![image](https://github.com/soranoo/next-css-obfuscator/assets/46896789/6c3c165a-a394-4ba5-ac8b-926e4ed5a7dd)

**Comment by hoangnhan2ka3** [comment]
yeah it's valid but I'm not use it yet and why it can replace the `filter` tag without `className` in front?

Maybe it's TW's error huh

**Comment by soranoo** [comment]
May I have a piece of the HTML code(after compilation) with the `filter` in it?

**Comment by hoangnhan2ka3** [comment]
U want a version with `filter` in `classIgnore` or not?

**Comment by soranoo** [comment]
The original version. (before obfuscation)

**Comment by hoangnhan2ka3** [comment]
`after compilation` and `before obfuscation`, u mean I should turn off your package and deploy it,right?

**Comment by hoangnhan2ka3** [comment]
wait for me @soranoo , I will share my project for u

**Comment by soranoo** [comment]
> `after compilation` and `before obfuscation`, u mean I should turn off your package and deploy it,right?

yes

**Comment by hoangnhan2ka3** [comment]
I just invited you @soranoo

**Comment by soranoo** [comment]
I can't reproduce the issue
![image](https://github.com/soranoo/next-css-obfuscator/assets/46896789/19642e46-9eb1-478e-b375-4be72308ea82)

**Comment by hoangnhan2ka3** [comment]
U mean u don't see this?

<img width="437" alt="Screenshot 2024-02-01 005433" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/598a77ad-8057-4e18-a769-ceeca974bf45">

**Comment by soranoo** [comment]
Try update to beta2 
> npm i next-css-obfuscator@beta

**Comment by hoangnhan2ka3** [comment]
yes, but...

<img width="185" alt="Screenshot 2024-02-01 040534" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/01a1513e-1c50-4178-82cc-b9a40db5c61c">

**Comment by hoangnhan2ka3** [comment]
Still nope

<img width="470" alt="Screenshot 2024-02-01 041027" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/b3cbe87c-8213-4b55-8a60-946f275693f5">

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/92e75356-059a-4d50-9cec-fe77cbbf5164)

<img width="133" alt="Screenshot 2024-02-01 041009" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/745723f2-6c33-4b59-9eee-34e1e5086f1c">

**Comment by hoangnhan2ka3** [comment]
ahh I know I know, please add to doc that user should/ must include

```
# css-obfucate
/css-obfuscator
/css-obfuscator/conversion.json
```

in there .gitignore file before deloy, otherwise it will get the data in the old `css-obfuscator` folder pushed to github:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/38157e8b-3e4a-4fa8-b8b4-ddbd8753fbef)

**Comment by hoangnhan2ka3** [comment]
Now you can go to [hoangnhan.co.uk/404](https://hoangnhan.co.uk/404) to see the `filter` issue of `.big` and `.small`

**Comment by hoangnhan2ka3** [comment]
I also used the same repo I just shared with you to deploy to hoangnhan.co.uk, I've just deleted the old `css-obfuscator` folder, please take a look to see if you can reproduce the error.

**Comment by soranoo** [comment]
Add the following to `next-css-obfuscator.config.cjs`
```js
// next-css-obfuscator.config.cjs

contentIgnoreRegexes: [
   /\.jsxs\)\("\w+"/g
]
```

**Comment by soranoo** [comment]
I will add this to doc and default config

**Comment by hoangnhan2ka3** [comment]
FIXED!

**Comment by hoangnhan2ka3** [comment]
You are very fanstatic @soranoo , I think I can safely build the project. If there are any problems, I will create an issue later 💕.
